import { ClientStatus, PlanName } from '../data/superAdminData';
import { Branding } from '../context/AuthContext';

export interface Client {
  id: string;
  name: string;
  contact: string;
  email: string;
  plan: PlanName;
  status: ClientStatus;
  modules: string[];
  addOns: string[];
  disabledCoreFeatures: string[];
  signupDate: string;
  mrr: number;
  locations: number;
  staff: number;
  branding: Branding;
  slug?: string;
  hasSmsConfig: boolean;
  smsSenderId?: string;
  alertsPhone?: string;
  trialEndsAt?: string;
  payhereSubscriptionId?: string;
  address?: string;
  phone?: string;
  taxId?: string;
  website?: string;
  taxRatePct: number;
  currency: string;
  fiscalYearStartMonth: number;
  numberingPrefixes: {
    invoice?: string;
    quotation?: string;
    purchaseOrder?: string;
    complaint?: string;
    expense?: string;
    return?: string;
    purchaseRequisition?: string;
    rfq?: string;
    supplierQuotation?: string;
    grn?: string;
    purchaseInvoice?: string;
    salesOrder?: string;
    deliveryNote?: string;
    salaryAdvance?: string;
    warrantyClaim?: string;
    supplierClaim?: string;
  };
}
