/**
 * Regenerates api/_lib/routes/table.ts by scanning every handler file under
 * api/_lib/routes/**. Run this any time a route is added, removed, or
 * renamed under api/_lib/routes/ — the single api/[...path].ts serverless
 * function (Vercel Hobby plan's 12-function cap made a real per-file router
 * impossible, see the plan history) depends entirely on this generated
 * table to know which handler serves which URL.
 *
 * Usage: npx tsx scripts/generate-route-table.ts
 */
import fs from 'fs';
import path from 'path';

const ROOT = process.cwd();
const ROUTES_DIR = path.join(ROOT, 'api', '_lib', 'routes');

function findRouteFiles(dir: string, base: string): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  let results: string[] = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results = results.concat(findRouteFiles(full, base));
    } else if (entry.name.endsWith('.ts') && entry.name !== 'table.ts') {
      results.push(path.relative(base, full).replace(/\\/g, '/'));
    }
  }
  return results;
}

interface RouteEntry {
  relPath: string;
  segments: string[];
  isDynamic: boolean[];
  paramNames: (string | null)[];
  importName: string;
  importPath: string;
}

function toRouteEntry(relPath: string, index: number): RouteEntry {
  const noExt = relPath.slice(0, -3); // strip .ts
  const parts = noExt.split('/');
  if (parts[parts.length - 1] === 'index') parts.pop();

  const segments: string[] = [];
  const isDynamic: boolean[] = [];
  const paramNames: (string | null)[] = [];
  for (const part of parts) {
    const m = part.match(/^\[(\w+)\]$/);
    if (m) {
      segments.push(part);
      isDynamic.push(true);
      paramNames.push(m[1]);
    } else {
      segments.push(part);
      isDynamic.push(false);
      paramNames.push(null);
    }
  }

  return {
    relPath,
    segments,
    isDynamic,
    paramNames,
    importName: `route${index}`,
    // .js, not .ts: this project is real ESM ("type":"module") and Vercel's
    // production build does NOT bundle this multi-file route tree into one
    // self-contained file (confirmed: 1211 separate compiled files in
    // .vercel/output) — Node's native runtime ESM loader requires an
    // explicit extension on every relative import, or it throws
    // ERR_MODULE_NOT_FOUND at request time (this broke the very first real
    // deploy after this router existed). Relative to this generated file,
    // which lives in api/_lib/routes/ itself.
    importPath: `./${noExt}.js`,
  };
}

const relFiles = findRouteFiles(ROUTES_DIR, ROUTES_DIR).sort();
const entries = relFiles.map(toRouteEntry);

// Report same-length literal-vs-dynamic collisions (informational — the
// router in api/[...path].ts resolves these correctly on its own by
// preferring the most-literal match, this is just visibility into where
// that logic actually matters).
const bySignature = new Map<string, RouteEntry[]>();
for (const e of entries) {
  const list = bySignature.get(String(e.segments.length)) ?? [];
  list.push(e);
  bySignature.set(String(e.segments.length), list);
}
let collisions = 0;
for (const list of bySignature.values()) {
  for (let i = 0; i < list.length; i++) {
    for (let j = i + 1; j < list.length; j++) {
      const a = list[i];
      const b = list[j];
      let sameShape = true;
      for (let k = 0; k < a.segments.length; k++) {
        if (!a.isDynamic[k] && !b.isDynamic[k] && a.segments[k] !== b.segments[k]) {
          sameShape = false;
          break;
        }
      }
      if (sameShape && a.segments.some((_, k) => a.isDynamic[k] !== b.isDynamic[k])) {
        collisions++;
        console.log(`Collision (resolved by literal-wins matching): ${a.relPath}  <->  ${b.relPath}`);
      }
    }
  }
}

const importLines = entries.map((e) => `import ${e.importName} from '${e.importPath}';`).join('\n');
const tableLines = entries
  .map((e) => {
    const segArr = e.segments.map((s, i) => (e.isDynamic[i] ? `{ param: '${e.paramNames[i]}' }` : `'${s}'`)).join(', ');
    return `  { segments: [${segArr}], handler: ${e.importName} }, // ${e.relPath}`;
  })
  .join('\n');

const output = `// GENERATED by scripts/generate-route-table.ts — do not hand-edit.
// Re-run \`npx tsx scripts/generate-route-table.ts\` after adding, removing,
// or renaming a file under api/_lib/routes/. See api/[...path].ts for the
// matcher that consumes this (most-literal-match-wins, so a route like
// customers/corporate-summary.ts always beats customers/[id].ts for that
// exact path).
import type { VercelRequest, VercelResponse } from '@vercel/node';

export type RouteSegment = string | { param: string };
export interface RouteDef {
  segments: RouteSegment[];
  handler: (req: VercelRequest, res: VercelResponse) => unknown;
}

${importLines}

export const ROUTES: RouteDef[] = [
${tableLines}
];
`;

fs.writeFileSync(path.join(ROUTES_DIR, 'table.ts'), output, 'utf8');
console.log(`\nWrote api/_lib/routes/table.ts with ${entries.length} entries (${collisions} collision(s) auto-resolved by specificity).`);
